# Generated by Django 5.2.3 on 2025-06-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_remove_userprofile_id_alter_userprofile_user'),
        ('stockhandler', '0002_alter_stock_base_price_alter_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockhandler.stock')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.userprofile')),
            ],
        ),
    ]
