# Generated by Django 5.2.3 on 2025-07-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockhandler', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amplitude',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='noise',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
